const datdot_vault = require('datdot-vault')
const datdot_chain = require('datdot-chain')
const chain_api = datdot_chain('http://localhost:8080')
const datdot_ui = require('datdot-ui')
const datdot_service = require('..')